### ISSUE TITLE
in_bst causes NoClassDefFoundError

### ISSUE THREAD

**Issue by maedoc** [brainstorm-tools/brainstorm3#666]
hi, first issue here, sorry if it's inappropriately filed, feel free to redirect. 

I haven't understood how Brainstorm does versioning or releases, so everything reported here, I redid today with version downloaded from the Brainstorm website (src & bin) today i.e. 23-12-08, despite the messages below reporting July 2023. 

I am trying to automate (and containerize) preprocessing of HCP MEG data following the tutorial.  This works with MCR and precompiled JAR so far *except* for the last step, where I have the following script to convert to a format that I can read in Python,
```matlab
%% find runs in protocol
protocol_path = '/tmp/brainstorm_db/hcp/data';
raw_bst_glob = [protocol_path '/*/*_notch_band_clean/data_0*.mat'];
raw_bst_fnames = dir(raw_bst_glob);

%% convert them
format compact
for i=1:size(raw_bst_fnames,1)
    f = raw_bst_fnames(i);
    fname = [f.folder filesep f.name]
    data = in_bst(fname);
    size(data.F)
    size(data.F(:,1:3:end))
    run_time = single(data.Time(1:3:end));
    run_data = single(data.F(:,1:3:end));
    save([f.folder filesep 'run_time.mat'], 'run_time');
    save([f.folder filesep 'run_data.mat'], 'run_data');
    size(run_data)
end
```
which works fine when run in MATLAB with Brainstorm open, but when run from the command line with the MCR, i.e.
```bash
!./brainstorm3-versions/231208/brainstorm3/bin/R2022b/brainstorm3.command /usr/local/MATLAB/MATLAB_Runtime/R2022b convert_all_runs.m
```
I get an error which seems unrelated:

```
*snip*

Exception in thread "EventMgr Dispatcher" java.lang.NoClassDefFoundError: com/mathworks/services/settings/SettingListenerfname =
    '/tmp/brainstorm_db/hcp/data/100307/@raw3-Restin_c_rfDC_notch_band_clean/data_0raw_3-Restin_c_rfDC_notch_band_clean.mat'

Caused by: java.lang.ClassNotFoundException: com.mathworks.services.settings.SettingListener

*snip*
```

full error (click the black triangle to expand). 
<details>
```
Please wait...
 
If it hangs for more than a few minutes: try pressing ENTER.
Alternatively, download Brainstorm for a different version of the Matlab Runtime.
(See the installation instructions on the Brainstorm website)
 
Gtk-Message: 15:31:13.776: Failed to load module "canberra-gtk-module"
 
BST> Starting Brainstorm:
BST> =================================
BST> BrainstormHomeDir = /home/duke/.mcrCache9.13/bst_ja0/bst_javabuil
BST> Version: 31-Jul-2023
BST> Deleting old process reports...
BST> Loading configuration file...
BST> Plugin brain2mesh: /home/duke/.mcrCache9.13/bst_ja0/Users/rcassani/.brainstorm/plugins/brain2mesh
BST> Plugin iso2mesh: /home/duke/.mcrCache9.13/bst_ja0/Users/rcassani/.brainstorm/plugins/iso2mesh
BST> Plugin brainentropy: /home/duke/.mcrCache9.13/bst_ja0/Users/rcassani/.brainstorm/plugins/brainentropy
BST> Plugin blackrock: /home/duke/.mcrCache9.13/bst_ja0/Users/rcassani/.brainstorm/plugins/blackrock
BST> Plugin neuroelectrics: /home/duke/.mcrCache9.13/bst_ja0/Users/rcassani/.brainstorm/plugins/neuroelectrics
BST> Plugin xdf: /home/duke/.mcrCache9.13/bst_ja0/Users/rcassani/.brainstorm/plugins/xdf
BST> Plugin libsvm: /home/duke/.mcrCache9.13/bst_ja0/Users/rcassani/.brainstorm/plugins/libsvm
BST> Plugin fastica: /home/duke/.mcrCache9.13/bst_ja0/Users/rcassani/.brainstorm/plugins/fastica
BST> Plugin picard: /home/duke/.mcrCache9.13/bst_ja0/Users/rcassani/.brainstorm/plugins/picard
BST> Plugin derivelfp: /home/duke/.mcrCache9.13/bst_ja0/Users/rcassani/.brainstorm/plugins/derivelfp
BST> Plugin nirstorm: /home/duke/.mcrCache9.13/bst_ja0/Users/rcassani/.brainstorm/plugins/nirstorm
BST> Plugin mcxlab-cl: /home/duke/.mcrCache9.13/bst_ja0/Users/rcassani/.brainstorm/plugins/mcxlab-cl
BST> Plugin mia: /home/duke/.mcrCache9.13/bst_ja0/Users/rcassani/.brainstorm/plugins/mia
BST> Plugin spm12: /home/duke/.mcrCache9.13/bst_ja0/Users/rcassani/.brainstorm/spmtrip
BST> Reading process folder...
BST> Loading current protocol...
BST> =================================
 
Exception in thread "EventMgr Dispatcher" java.lang.NoClassDefFoundError: com/mathworks/services/settings/SettingListenerfname =
    '/tmp/brainstorm_db/hcp/data/100307/@raw3-Restin_c_rfDC_notch_band_clean/data_0raw_3-Restin_c_rfDC_notch_band_clean.mat'

Caused by: java.lang.ClassNotFoundException: com.mathworks.services.settings.SettingListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
Exception in thread "EventMgr Dispatcher" java.lang.NoClassDefFoundError: com/mathworks/services/settings/SettingListener
Caused by: java.lang.ClassNotFoundException: com.mathworks.services.settings.SettingListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

--------------------------------------------------------------------------------
          Segmentation violation detected at 2023-12-08 15:31:22 +0100
--------------------------------------------------------------------------------

Configuration:
  Crash Decoding           : Disabled - No sandbox or build area path
  Crash Mode               : continue (default)
  Default Encoding         : UTF-8
  Deployed                 : true
  Desktop Environment      : ubuntu:GNOME
  GNU C Library            : 2.35 stable
  Graphics Driver          : Uninitialized hardware 
  Graphics card 1          : 0x10de ( 0x10de ) 0x1eb0 Version 535.129.3.0 (0-0-0)
  Java Version             : Java 1.8.0_202-b08 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
  MATLAB Architecture      : glnxa64
  MATLAB Entitlement ID    : Unknown
  MATLAB Root              : /usr/local/MATLAB/MATLAB_Runtime/R2022b
  MATLAB Version           : 9.13.0.2399474 (R2022b) Update 7
  OpenGL                   : hardware
  Operating System         : Ubuntu 22.04.3 LTS
  Process ID               : 41095
  Processor ID             : x86 Family 6 Model 85 Stepping 4, GenuineIntel
  Session Key              : c6a9da94-7568-4fcf-b750-04ba0b4076d1
  Window System            : The X.Org Foundation (12101004), display :1

Fault Count: 1


Abnormal termination:
Segmentation violation

Current Thread: 'ED 0 dispatch t' id 139903570540096

Register State (from fault):
  RAX = 0000000000000000  RBX = 00007f3dc4a57800
  RCX = 00007f3dd69fe598  RDX = 00007f3f17dc7f98
  RSP = 00007f3dd69fe4d0  RBP = 00007f3dd69fe580
  RSI = 00007f3ddaffe3a0  RDI = 00007f3dc4a57800

   R8 = 00007f3db80068f0   R9 = 00007f3db8006908
  R10 = 00007f3ee8416dd0  R11 = 00007f3ee85fe490
  R12 = 00007f3dc4a579f8  R13 = 00007f3dc4a579f8
  R14 = 0000000000000000  R15 = 00007f3dd69fe598

  RIP = 00007f3f174d0ef6  EFL = 0000000000010246

   CS = 0033   FS = 0000   GS = 0000

Stack Trace (from fault):
[  0] 0x00007f3f174d0ef6 /usr/local/MATLAB/MATLAB_Runtime/R2022b/sys/java/jre/glnxa64/jre/lib/amd64/server/libjvm.so+07147254
[  1] 0x00007f3ee85fe511 /usr/local/MATLAB/MATLAB_Runtime/R2022b/bin/glnxa64/libnativemcl.so+02090257 _ZN7JNIEnv_16CallObjectMethodEP8_jobjectP10_jmethodIDz+00000129
[  2] 0x00007f3de41e37c9 /usr/local/MATLAB/MATLAB_Runtime/R2022b/bin/glnxa64/libnativesettings.so+00169929
[  3] 0x00007f3de41e3d94 /usr/local/MATLAB/MATLAB_Runtime/R2022b/bin/glnxa64/libnativesettings.so+00171412
[  4] 0x00007f3de41ef0d3 /usr/local/MATLAB/MATLAB_Runtime/R2022b/bin/glnxa64/libnativesettings.so+00217299 _ZN7mwboost6detail8function26void_function_obj_invoker1IZN14nativesettings16registerListenerIN8settings4core24SettingsValueChangeEventEFvRKNS_10shared_ptrI8_jobjectEERKS7_SC_EEEvPT0_RKNS8_INS6_8SettingsEEESC_SC_RKSt4pairISA_NS_8weak_ptrINS6_6detail16SettingsNodeImplEEEEPN10foundation7msg_svc10threadutil20ConcurrentTBBHashMapINSW_13ConcurrentMapISR_NS8_INSV_8eventmgr16ScopedConnectionEEEEEEEEUlSE_E_vSE_E6invokeERNS1_15function_bufferESE_+00000051
[  5] 0x00007f3eebe53bc0 /usr/local/MATLAB/MATLAB_Runtime/R2022b/bin/glnxa64/libmwsettings_in_matlab.so+00203712 _ZN7mwboost6detail8function26void_function_obj_invoker1IZN10foundation7msg_svc8eventmgr8EventMgr9subscribeIN8settings4core24SettingsValueChangeEventENS_9function1IvRKSA_EEN9__gnu_cxx17__normal_iteratorIPKNSt7__cxx1112basic_stringIDsSt11char_traitsIDsESaIDsEEESt6vectorISM_SaISM_EEEEEESt10unique_ptrINS5_10ConnectionESt14default_deleteISU_EERKT0_T1_S11_EUlRKNS5_9BaseEventEE_vS14_E6invokeERNS1_15function_bufferES14_+00000240
[  6] 0x00007f3ee0cb837e /usr/local/MATLAB/MATLAB_Runtime/R2022b/bin/glnxa64/libmwms.so+02851710 _ZN10foundation7msg_svc8eventmgr6detail10UserCbPack6invokeERKNS1_9BaseEventE+00000414
[  7] 0x00007f3ee0cd4751 /usr/local/MATLAB/MATLAB_Runtime/R2022b/bin/glnxa64/libmwms.so+02967377
[  8] 0x00007f3ee0cd4c88 /usr/local/MATLAB/MATLAB_Runtime/R2022b/bin/glnxa64/libmwms.so+02968712
[  9] 0x00007f3ee0cea40a /usr/local/MATLAB/MATLAB_Runtime/R2022b/bin/glnxa64/libmwms.so+03056650
[ 10] 0x00007f3ee0ccf73f /usr/local/MATLAB/MATLAB_Runtime/R2022b/bin/glnxa64/libmwms.so+02946879
[ 11] 0x00007f3ee0cd183b /usr/local/MATLAB/MATLAB_Runtime/R2022b/bin/glnxa64/libmwms.so+02955323
[ 12] 0x00007f3ee0cd1fd1 /usr/local/MATLAB/MATLAB_Runtime/R2022b/bin/glnxa64/libmwms.so+02957265
[ 13] 0x00007f3eeb00942f /usr/local/MATLAB/MATLAB_Runtime/R2022b/bin/glnxa64/libmwboost_thread.so.1.75.0+00037935
[ 14] 0x00007f3f17e94ac3                    /lib/x86_64-linux-gnu/libc.so.6+00608963
[ 15] 0x00007f3f17f26a40                    /lib/x86_64-linux-gnu/libc.so.6+01206848

** This crash report has been saved to disk as /home/duke/matlab_crash_dump.41095-1 **



MATLAB is exiting because of fatal error
./brainstorm3-versions/231208/brainstorm3/bin/R2022b/brainstorm3.command: line 145: 41095 Killed                  "$JAVA_EXE" -jar "$JAR_FILE" "${@:2}"
```
</details>

Might this be a problem with how I'm using `in_bst`?  The other scripts I've used to run bst processes don't have this problem.  Alternatively, is there a better way to export full raw runs? I am considering for instance just porting the in_fread_bst routine but prefer to avoid it.

Thanks in advance

**Comment by maedoc** [comment]
sorry for the noise, it was `format compact` that was triggering the error, nothing to do with Brainstorm at all.
